# Generated by cucumber-sinatra. (2011-09-04 02:04:20 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'wwwjdic.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Wwwjdic

class WwwjdicWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  WwwjdicWorld.new
end
